import type { DistributionDraft, ReceiptBatch } from './types'

export const seedDrafts: DistributionDraft[] = [
  {
    id: 'DR-001',
    workId: 'W-001',
    work: '《远山回声》',
    territory: '中国大陆',
    windows: [
      { id: 'DR-001-W1', channel: '星海影院', rights: '院线', start: '2026-10-18', end: '2026-12-05' },
      { id: 'DR-001-W2', channel: '云帆视频', rights: '流媒体', start: '2026-11-20', end: '2027-11-19' },
    ],
    exclusivity: { exclusive: true, channels: ['星海影院', '云帆视频'], languages: ['简体中文'], subTerritories: ['全国'] },
    materials: [
      { code: 'MAT-CN-01', name: '院线正式海报', locale: 'zh-CN' },
      { code: 'MAT-CN-02', name: '流媒体预告片 90s', locale: 'zh-CN' },
    ],
    version: 18,
    status: '已确认',
    snapshot: {
      id: 'AP-18',
      version: 18,
      approver: '黎清（法务）',
      approvedAt: '2026-09-20 16:35',
      windows: [
        { channel: '星海影院', rights: '院线', start: '2026-10-18', end: '2026-12-05' },
        { channel: '云帆视频', rights: '流媒体', start: '2026-11-20', end: '2027-11-19' },
      ],
      exclusivity: { exclusive: true, channels: ['星海影院', '云帆视频'], languages: ['简体中文'], subTerritories: ['全国'] },
      materials: [
        { code: 'MAT-CN-01', name: '院线正式海报', locale: 'zh-CN' },
        { code: 'MAT-CN-02', name: '流媒体预告片 90s', locale: 'zh-CN' },
      ],
      windowDigest: '',
      exclusivityDigest: '',
      materialDigest: '',
      valid: true,
      invalidatedAt: null,
      invalidatedReason: null,
    },
    materialPackage: { id: 'PKG-18', items: [{ code: 'MAT-CN-01', name: '院线正式海报', locale: 'zh-CN' }, { code: 'MAT-CN-02', name: '流媒体预告片 90s', locale: 'zh-CN' }], digest: '', status: '有效', snapshotVersion: 18, updatedAt: '2026-09-20 16:35' },
    updatedAt: '2026-09-20 16:35',
  },
  {
    id: 'DR-002',
    workId: 'W-002',
    work: '《深港口岸》',
    territory: '新加坡',
    windows: [{ id: 'DR-002-W1', channel: '云帆视频', rights: '流媒体', start: '2026-12-01', end: '2027-05-31' }],
    exclusivity: { exclusive: true, channels: ['云帆视频'], languages: ['英文', '简体中文'], subTerritories: ['新加坡全境'] },
    materials: [{ code: 'MAT-SG-01', name: '流媒体正式海报', locale: 'en-SG' }],
    version: 9,
    status: '已确认',
    snapshot: {
      id: 'AP-9',
      version: 9,
      approver: '章宁（发行）',
      approvedAt: '2026-09-18 10:02',
      windows: [{ channel: '云帆视频', rights: '流媒体', start: '2026-12-01', end: '2027-05-31' }],
      exclusivity: { exclusive: true, channels: ['云帆视频'], languages: ['英文', '简体中文'], subTerritories: ['新加坡全境'] },
      materials: [{ code: 'MAT-SG-01', name: '流媒体正式海报', locale: 'en-SG' }],
      windowDigest: '',
      exclusivityDigest: '',
      materialDigest: '',
      valid: true,
      invalidatedAt: null,
      invalidatedReason: null,
    },
    materialPackage: { id: 'PKG-9', items: [{ code: 'MAT-SG-01', name: '流媒体正式海报', locale: 'en-SG' }], digest: '', status: '有效', snapshotVersion: 9, updatedAt: '2026-09-18 10:02' },
    updatedAt: '2026-09-18 10:02',
  },
]

/** 回执只写 payload + present，指纹由 normalizePages 统一回填 */
export const seedBatches: ReceiptBatch[] = [
  {
    id: 'RC-301',
    workId: 'W-001',
    work: '《远山回声》',
    territory: '中国大陆',
    source: '云帆视频 · 法务部',
    receivedAt: '2026-09-28 09:12',
    status: '待处理',
    attempts: 0,
    lastError: null,
    mergedDraftId: null,
    mergedVersion: null,
    pages: [
      {
        code: '窗口页', present: true, digest: '',
        payload: { windows: [
          { channel: '星海影院', rights: '院线', start: '2026-10-18', end: '2026-12-05' },
          { channel: '云帆视频', rights: '流媒体', start: '2026-12-06', end: '2027-12-05' },
        ] },
      },
      {
        code: '独占范围页', present: true, digest: '',
        payload: { exclusivity: { exclusive: true, channels: ['云帆视频'], languages: ['简体中文'], subTerritories: ['全国'] } },
      },
      {
        code: '物料清单页', present: true, digest: '',
        payload: { materials: [
          { code: 'MAT-CN-01', name: '院线正式海报', locale: 'zh-CN' },
          { code: 'MAT-CN-02', name: '流媒体预告片 90s', locale: 'zh-CN' },
        ] },
      },
    ],
  },
  {
    id: 'RC-302',
    workId: 'W-001',
    work: '《远山回声》',
    territory: '中国大陆',
    source: '南华卫视 · 合同科',
    receivedAt: '2026-09-28 11:40',
    status: '合并失败',
    attempts: 1,
    lastError: '缺页：独占范围页、物料清单页',
    mergedDraftId: null,
    mergedVersion: null,
    pages: [
      { code: '窗口页', present: true, digest: '', payload: { windows: [{ channel: '南华卫视', rights: '电视', start: '2027-01-08', end: '2027-03-31' }] } },
      { code: '独占范围页', present: false, digest: null },
      { code: '物料清单页', present: false, digest: null },
    ],
  },
  {
    id: 'RC-303',
    workId: 'W-002',
    work: '《深港口岸》',
    territory: '新加坡',
    source: '云帆视频 · 新加坡发行',
    receivedAt: '2026-09-27 15:20',
    status: '待处理',
    attempts: 0,
    lastError: null,
    mergedDraftId: null,
    mergedVersion: null,
    pages: [
      { code: '窗口页', present: true, digest: '', payload: { windows: [{ channel: '云帆视频', rights: '流媒体', start: '2026-12-01', end: '2027-05-31' }] } },
      { code: '独占范围页', present: true, digest: '', payload: { exclusivity: { exclusive: true, channels: ['云帆视频'], languages: ['英文', '简体中文'], subTerritories: ['新加坡全境'] } } },
      { code: '物料清单页', present: true, digest: '', payload: { materials: [
        { code: 'MAT-SG-01', name: '流媒体正式海报', locale: 'en-SG' },
        { code: 'MAT-SG-02', name: '角色特辑海报', locale: 'en-SG' },
      ] } },
    ],
  },
  {
    id: 'RC-304',
    workId: 'W-001',
    work: '《远山回声》',
    territory: '中国香港',
    source: '寰亚影视 · 海外发行',
    receivedAt: '2026-09-29 08:05',
    status: '待处理',
    attempts: 0,
    lastError: null,
    mergedDraftId: null,
    mergedVersion: null,
    pages: [
      { code: '窗口页', present: true, digest: '', payload: { windows: [{ channel: '寰亚院线', rights: '院线', start: '2026-11-02', end: '2026-12-20' }] } },
      { code: '独占范围页', present: true, digest: '', payload: { exclusivity: { exclusive: true, channels: ['寰亚院线'], languages: ['繁体中文'], subTerritories: ['香港全境'] } } },
      { code: '物料清单页', present: true, digest: '', payload: { materials: [{ code: 'MAT-HK-01', name: '港式院线海报', locale: 'zh-HK' }] } },
    ],
  },
]
